/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

/**
 *
 * @author Windows 11
 */
public class Lib_CienciaFiccion extends javax.swing.JFrame {

    /**
     * Creates new form Lib_CienciaFiccion
     */
    public Lib_CienciaFiccion() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtb_aventura = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jtb_cuento = new javax.swing.JButton();
        jtb_c = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jtb_o = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jtb_m = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jtb_p = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jtb_r = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtb_menu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtb_aventura.setText("Aventura");
        jtb_aventura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_aventuraActionPerformed(evt);
            }
        });

        jLabel14.setText("Precio");

        jtb_cuento.setText("Cuento de Hadas");
        jtb_cuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_cuentoActionPerformed(evt);
            }
        });

        jtb_c.setText("Comprar");
        jtb_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_cActionPerformed(evt);
            }
        });

        jLabel15.setText("Precio");

        jtb_o.setText("Comprar");
        jtb_o.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_oActionPerformed(evt);
            }
        });

        jLabel16.setText("Precio");

        jtb_m.setText("Comprar");
        jtb_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_mActionPerformed(evt);
            }
        });

        jLabel17.setText("Precio");

        jtb_p.setText("Comprar");
        jtb_p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_pActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows 11\\Documents\\logo2.jpg")); // NOI18N

        jLabel18.setText("Precio");

        jtb_r.setText("Comprar");
        jtb_r.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_rActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/un mundo feliz.jpg"))); // NOI18N

        jLabel5.setText("Descripción:");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/la maquina del tiempo.jpg"))); // NOI18N

        jLabel7.setText("Descripción:");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cronicas marcianas.jpg"))); // NOI18N

        jLabel9.setText("Descripción:");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/yo, robot.jpg"))); // NOI18N

        jLabel11.setText("Descripción:");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/soy leyenda.jpg"))); // NOI18N

        jLabel13.setText("Descripción:");

        jtb_menu.setText("< Menú Principal");
        jtb_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_menuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(427, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(114, 114, 114))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(118, 118, 118))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtb_o)
                            .addComponent(jtb_c)
                            .addComponent(jtb_m)
                            .addComponent(jtb_p)
                            .addComponent(jtb_r))
                        .addGap(92, 92, 92))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(119, 119, 119))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(115, 115, 115))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jtb_menu)
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(116, 116, 116))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(181, 181, 181)
                            .addComponent(jtb_aventura)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtb_cuento)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(70, 70, 70)
                                    .addComponent(jLabel7))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel9))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel10))
                                    .addGap(6, 6, 6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel11))))
                            .addGap(456, 456, 456)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtb_c)
                .addGap(48, 48, 48)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jtb_o)
                .addGap(53, 53, 53)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtb_m)
                .addGap(29, 29, 29)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jtb_p)
                .addGap(28, 28, 28)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jtb_r)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jtb_menu)
                .addGap(31, 31, 31))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jtb_aventura)
                                .addComponent(jtb_cuento))))
                    .addGap(30, 30, 30)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addGap(34, 34, 34)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addGap(3, 40, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9))
                    .addGap(45, 45, 45)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel11)
                        .addComponent(jLabel10))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel12)
                        .addComponent(jLabel13))
                    .addGap(74, 74, 74)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtb_aventuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_aventuraActionPerformed
        Lib_Aventura verLib_Aventura = new Lib_Aventura();
        verLib_Aventura.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jtb_aventuraActionPerformed

    private void jtb_cuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_cuentoActionPerformed
        Lib_CuentodeHadas verLib_CuentodeHadas = new Lib_CuentodeHadas();
        verLib_CuentodeHadas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jtb_cuentoActionPerformed

    private void jtb_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_cActionPerformed
        Forma_Pago ventana = new Forma_Pago();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jtb_cActionPerformed

    private void jtb_oActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_oActionPerformed
        Forma_Pago ventana = new Forma_Pago();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jtb_oActionPerformed

    private void jtb_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_mActionPerformed
        Forma_Pago ventana = new Forma_Pago();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jtb_mActionPerformed

    private void jtb_pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_pActionPerformed
        Forma_Pago ventana = new Forma_Pago();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jtb_pActionPerformed

    private void jtb_rActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_rActionPerformed
        Forma_Pago ventana = new Forma_Pago();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jtb_rActionPerformed

    private void jtb_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_menuActionPerformed
        MenuPrincipal ventana = new MenuPrincipal();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jtb_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lib_CienciaFiccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lib_CienciaFiccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lib_CienciaFiccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lib_CienciaFiccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lib_CienciaFiccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jtb_aventura;
    private javax.swing.JButton jtb_c;
    private javax.swing.JButton jtb_cuento;
    private javax.swing.JButton jtb_m;
    private javax.swing.JButton jtb_menu;
    private javax.swing.JButton jtb_o;
    private javax.swing.JButton jtb_p;
    private javax.swing.JButton jtb_r;
    // End of variables declaration//GEN-END:variables
}
