/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

/**
 *
 * @author Windows 11
 */
public class Lib_Aventura extends javax.swing.JFrame {

    /**
     * Creates new form Lib_Aventura
     */
    public Lib_Aventura() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtb_menu = new javax.swing.JButton();
        jtb_ciencia = new javax.swing.JButton();
        jtb_cuento = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jtb_c = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jtb_o = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jtb_m = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jtb_p = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jtb_r = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows 11\\Documents\\logo2.jpg")); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Robinson-Crusoe.jpg"))); // NOI18N

        jLabel5.setText("Descripción:");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/la vuelta al mundo.jpg"))); // NOI18N

        jLabel7.setText("Descripción:");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Tigre mompracem1.jpg"))); // NOI18N

        jLabel9.setText("Descripción:");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/colmillo blanco1.jpg"))); // NOI18N

        jLabel11.setText("Descripción:");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/los tres mosqueteros.jpg"))); // NOI18N

        jLabel13.setText("Descripción:");

        jtb_menu.setText("< Menú Principal");
        jtb_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_menuActionPerformed(evt);
            }
        });

        jtb_ciencia.setText("Ciencia Ficción");
        jtb_ciencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_cienciaActionPerformed(evt);
            }
        });

        jtb_cuento.setText("Cuento de Hadas");
        jtb_cuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_cuentoActionPerformed(evt);
            }
        });

        jLabel14.setText("Precio");

        jtb_c.setText("Comprar");
        jtb_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_cActionPerformed(evt);
            }
        });

        jLabel15.setText("Precio");

        jtb_o.setText("Comprar");
        jtb_o.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_oActionPerformed(evt);
            }
        });

        jLabel16.setText("Precio");

        jtb_m.setText("Comprar");
        jtb_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_mActionPerformed(evt);
            }
        });

        jLabel17.setText("Precio");

        jtb_p.setText("Comprar");
        jtb_p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_pActionPerformed(evt);
            }
        });

        jLabel18.setText("Precio");

        jtb_r.setText("Comprar");
        jtb_r.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_rActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(181, 181, 181)
                .addComponent(jtb_ciencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtb_cuento)
                .addGap(7, 7, 7)
                .addComponent(jLabel14)
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addComponent(jLabel12)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(79, 79, 79)
                                        .addComponent(jLabel3))
                                    .addComponent(jLabel13))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(105, 105, 105))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtb_menu)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtb_r)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtb_m)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtb_o)
                                        .addComponent(jtb_c))
                                    .addComponent(jtb_p))))
                        .addGap(83, 83, 83))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtb_ciencia)
                            .addComponent(jtb_cuento))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtb_c)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel15))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(59, 59, 59))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jtb_o)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel16))
                                .addGap(18, 18, 18)
                                .addComponent(jtb_m)))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel17))
                                .addGap(18, 18, 18)
                                .addComponent(jtb_p))
                            .addComponent(jLabel10))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addComponent(jtb_r)))
                .addGap(42, 42, 42)
                .addComponent(jtb_menu)
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtb_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_menuActionPerformed
        MenuPrincipal ventana = new MenuPrincipal();
       ventana.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jtb_menuActionPerformed

    private void jtb_cuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_cuentoActionPerformed
         Lib_CuentodeHadas verLib_CuentodeHadas = new Lib_CuentodeHadas();
       verLib_CuentodeHadas.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jtb_cuentoActionPerformed

    private void jtb_cienciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_cienciaActionPerformed
        Lib_CienciaFiccion verLib_CienciaFiccion = new Lib_CienciaFiccion();
       verLib_CienciaFiccion.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jtb_cienciaActionPerformed

    private void jtb_pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_pActionPerformed
       Forma_Pago ventana = new Forma_Pago();
       ventana.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jtb_pActionPerformed

    private void jtb_rActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_rActionPerformed
        Forma_Pago ventana = new Forma_Pago();
       ventana.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jtb_rActionPerformed

    private void jtb_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_cActionPerformed
       Forma_Pago ventana = new Forma_Pago();
       ventana.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jtb_cActionPerformed

    private void jtb_oActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_oActionPerformed
        Forma_Pago ventana = new Forma_Pago();
       ventana.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jtb_oActionPerformed

    private void jtb_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_mActionPerformed
        Forma_Pago ventana = new Forma_Pago();
       ventana.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jtb_mActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lib_Aventura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lib_Aventura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lib_Aventura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lib_Aventura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lib_Aventura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JButton jtb_c;
    private javax.swing.JButton jtb_ciencia;
    private javax.swing.JButton jtb_cuento;
    private javax.swing.JButton jtb_m;
    private javax.swing.JButton jtb_menu;
    private javax.swing.JButton jtb_o;
    private javax.swing.JButton jtb_p;
    private javax.swing.JButton jtb_r;
    // End of variables declaration//GEN-END:variables
}
